# security/ai_safety.yaml
apiVersion: security.phasma.ai/v1alpha1
kind: AISafetyPolicy
metadata:
  name: phasma-safety-v1
  namespace: phasma-prod
spec:
  ### Model Governance ###
  modelMonitoring:
    biasDetection:
      enabled: true
      interval: 5m
      thresholds:
        disparateImpact: 0.8
        statisticalParity: 0.1
    driftDetection:
      featureImportanceThreshold: 0.15
      predictionDistributionDelta: 0.2
  
  ### Content Safety ###  
  contentFilters:
    inputSanitization:
      regexPatterns:
        - name: PII_DETECTION
          pattern: \b\d{3}[-.]?\d{3}[-.]?\d{4}\b|\b\d{5}\b
          action: REDACT
        - name: TOXICITY
          pattern: \b(kill|hate|terrorist)\b
          action: BLOCK
    outputValidation:
      ethicalGuidelines:
        - principle: nonMaleficence
          enforcementLevel: STRICT
        - principle: fairness
          enforcementLevel: ADVISORY

  ### Operational Security ###
  runtimeProtection:
    adversarialDetection:
      modelShield: true
      inputObfuscationLevel: 3
    apiSecurity:
      requestValidation:
        schemaEnforcement: STRICT
        maxPayloadSize: 5MB
      rateLimiting:
        rps: 100
        burstCapacity: 150

  ### Data Privacy ###
  privacyEnclaves:
    encryptedDataPaths:
      - /var/phasma/sensitive/*
    differentialPrivacy:
      epsilon: 0.5
      delta: 1e-5
    anonymization:
      kAnonymity: 3
      lDiversity: 2

  ### Access Control ###  
  authorization:
    roleBasedAccess:
      modelDevelopers:
        - operations: [TRAIN, DEPLOY]
          resources: [llm/*]
      auditors:
        - operations: [MONITOR, AUDIT]
          resources: [*]
    attributeBasedAccess:
      requiredClaims:
        - department: ai-safety
        - clearanceLevel: 5
  
  ### Audit & Compliance ###
  auditTrail:
    immutableLogging:
      retentionPeriod: 7y
      tamperEvidence: CRYPTOGRAPHIC
    regulatoryMapping:
      GDPR:
        article32: true
        article35: true
      HIPAA:
        safeHarbor: true

  ### Failure Protocols ###
  safetyInterlocks:
    killSwitches:
      - trigger: 
          condition: biasScore > 0.25
        action: DISABLE_MODEL
      - trigger:
          condition: piiLeakageDetected
        action: QUARANTINE_DATA
    fallbackSystems:
      defaultResponse: "Safety protocol engaged"
      gracefulDegradation: LEVEL2

  ### Cryptographic Controls ###
  cryptoEnforcement:
    modelSigning:
      required: true
      allowedIssuers:
        - phasma-root-ca
    inferenceProvenance:
      timestampHashing: CHAINED
      nonceRotation: 15m

  ### Resource Constraints ###  
  executionBoundaries:
    computeGuardrails:
      maxInferenceTime: 2s
      maxMemoryUsage: 4Gi
    geographicFencing:
      allowedRegions: [NA, EU]
      blockingCountries: [CN, RU]

  ### Update Policies ###
  lifecycleManagement:
    autoPatch:
      criticalCVEs: IMMEDIATE
      highCVEs: 24h
    deprecatedModels:
      sunsetPeriod: 30d
      archivalProtocol: CRYPTOGRAPHIC_WIPE
